<?php

/**
 * Implements hook_enable().
 * Provides an upgrade path from Drupal 6.x sites to Drupal 7.x,
 * checking to see if the site_footer variable has been set for a D6 site,
 * if so - grab that value and pass to our new footer variable.
 */
function footer_message_enable() {
	$site_footer = variable_get('site_footer', FALSE);
	if ($site_footer) {
		variable_set('footer_message_msg', array('value' => $site_footer));
	}
}